
package proyectocubo;


public class FormCubo extends javax.swing.JFrame {

    //Las caras del cubo.
        public static int C1[][] = {
        {0,0,0,0},
        {0,11,12,13},
        {0,14,15,16},
        {0,17,18,19}};
    
        public static int C2[][] = {
        {0,0,0,0},
        {0,21,22,23},
        {0,24,25,26},
        {0,27,28,29}};
        
        public static int C3[][] = {
        {0,0,0,0},
        {0,31,32,33},
        {0,34,35,36},
        {0,37,38,39}};
    
        public static int C4[][] = {
        {0,0,0,0},
        {0,41,42,43},
        {0,44,45,46},
        {0,47,48,49}};
    
        public static int C5[][] = {
        {0,0,0,0},
        {0,51,52,53},
        {0,54,55,56},
        {0,57,58,59}};
        
        public static int C6[][] = {
        {0,0,0,0},
        {0,61,62,63},
        {0,64,65,66},
        {0,67,68,69}};
   
        
    public FormCubo() {
        initComponents();
    }
    
    
    
    void EtiquetasOn(){
        
        
        Txt1_11.setText(String.valueOf(C1[1][1]));
        Txt2_11.setText(String.valueOf(C2[1][1]));
        
        
        
        
    }//Fin del Metodo On
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Txt1_11 = new javax.swing.JTextField();
        Txt1_12 = new javax.swing.JTextField();
        Txt1_13 = new javax.swing.JTextField();
        Txt1_21 = new javax.swing.JTextField();
        Txt1_22 = new javax.swing.JTextField();
        Txt1_23 = new javax.swing.JTextField();
        Txt1_31 = new javax.swing.JTextField();
        Txt1_32 = new javax.swing.JTextField();
        Txt1_33 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        Txt2_11 = new javax.swing.JTextField();
        Txt2_22 = new javax.swing.JTextField();
        Txt2_23 = new javax.swing.JTextField();
        Txt2_24 = new javax.swing.JTextField();
        Txt2_25 = new javax.swing.JTextField();
        Txt2_26 = new javax.swing.JTextField();
        Txt2_27 = new javax.swing.JTextField();
        Txt2_28 = new javax.swing.JTextField();
        Txt2_29 = new javax.swing.JTextField();
        Btn_EtiquetasOn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Txt1_11.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Txt1_11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Txt1_11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt1_11ActionPerformed(evt);
            }
        });

        Txt1_12.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Txt1_12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Txt1_12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt1_12ActionPerformed(evt);
            }
        });

        Txt1_13.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Txt1_13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Txt1_13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt1_13ActionPerformed(evt);
            }
        });

        Txt1_21.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Txt1_21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Txt1_21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt1_21ActionPerformed(evt);
            }
        });

        Txt1_22.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Txt1_22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Txt1_22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt1_22ActionPerformed(evt);
            }
        });

        Txt1_23.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Txt1_23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Txt1_23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt1_23ActionPerformed(evt);
            }
        });

        Txt1_31.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Txt1_31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Txt1_31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt1_31ActionPerformed(evt);
            }
        });

        Txt1_32.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Txt1_32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Txt1_32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt1_32ActionPerformed(evt);
            }
        });

        Txt1_33.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Txt1_33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Txt1_33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt1_33ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Txt1_11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(Txt1_12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(Txt1_13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Txt1_31, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(Txt1_32, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(Txt1_33, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Txt1_21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(Txt1_22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(Txt1_23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt1_11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt1_12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt1_13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt1_21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt1_22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt1_23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt1_32, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt1_31, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt1_33, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Txt2_11.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Txt2_11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Txt2_11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt2_11ActionPerformed(evt);
            }
        });

        Txt2_22.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Txt2_22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Txt2_22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt2_22ActionPerformed(evt);
            }
        });

        Txt2_23.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Txt2_23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Txt2_23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt2_23ActionPerformed(evt);
            }
        });

        Txt2_24.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Txt2_24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Txt2_24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt2_24ActionPerformed(evt);
            }
        });

        Txt2_25.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Txt2_25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Txt2_25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt2_25ActionPerformed(evt);
            }
        });

        Txt2_26.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Txt2_26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Txt2_26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt2_26ActionPerformed(evt);
            }
        });

        Txt2_27.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Txt2_27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Txt2_27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt2_27ActionPerformed(evt);
            }
        });

        Txt2_28.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Txt2_28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Txt2_28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt2_28ActionPerformed(evt);
            }
        });

        Txt2_29.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Txt2_29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Txt2_29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt2_29ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Txt2_11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(Txt2_22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(Txt2_23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Txt2_27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(Txt2_28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(Txt2_29, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Txt2_24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(Txt2_25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(Txt2_26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt2_11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt2_22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt2_23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt2_24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt2_25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt2_26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt2_28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt2_27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt2_29, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Btn_EtiquetasOn.setText("On");
        Btn_EtiquetasOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EtiquetasOnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(170, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Btn_EtiquetasOn)
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Btn_EtiquetasOn)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txt1_11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt1_11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt1_11ActionPerformed

    private void Txt1_12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt1_12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt1_12ActionPerformed

    private void Txt1_13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt1_13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt1_13ActionPerformed

    private void Txt1_21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt1_21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt1_21ActionPerformed

    private void Txt1_22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt1_22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt1_22ActionPerformed

    private void Txt1_23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt1_23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt1_23ActionPerformed

    private void Txt1_31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt1_31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt1_31ActionPerformed

    private void Txt1_32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt1_32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt1_32ActionPerformed

    private void Txt1_33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt1_33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt1_33ActionPerformed

    private void Txt2_11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt2_11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt2_11ActionPerformed

    private void Txt2_22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt2_22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt2_22ActionPerformed

    private void Txt2_23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt2_23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt2_23ActionPerformed

    private void Txt2_24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt2_24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt2_24ActionPerformed

    private void Txt2_25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt2_25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt2_25ActionPerformed

    private void Txt2_26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt2_26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt2_26ActionPerformed

    private void Txt2_27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt2_27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt2_27ActionPerformed

    private void Txt2_28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt2_28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt2_28ActionPerformed

    private void Txt2_29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt2_29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt2_29ActionPerformed

    private void Btn_EtiquetasOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EtiquetasOnActionPerformed
        // TODO add your handling code here:
        EtiquetasOn();
    }//GEN-LAST:event_Btn_EtiquetasOnActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCubo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCubo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCubo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCubo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCubo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_EtiquetasOn;
    private javax.swing.JTextField Txt1_11;
    private javax.swing.JTextField Txt1_12;
    private javax.swing.JTextField Txt1_13;
    private javax.swing.JTextField Txt1_21;
    private javax.swing.JTextField Txt1_22;
    private javax.swing.JTextField Txt1_23;
    private javax.swing.JTextField Txt1_31;
    private javax.swing.JTextField Txt1_32;
    private javax.swing.JTextField Txt1_33;
    private javax.swing.JTextField Txt2_11;
    private javax.swing.JTextField Txt2_22;
    private javax.swing.JTextField Txt2_23;
    private javax.swing.JTextField Txt2_24;
    private javax.swing.JTextField Txt2_25;
    private javax.swing.JTextField Txt2_26;
    private javax.swing.JTextField Txt2_27;
    private javax.swing.JTextField Txt2_28;
    private javax.swing.JTextField Txt2_29;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
